import { ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export function StripeOfferCard({ checkoutUrl }: { checkoutUrl: string }) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Stripe-Powered Offer</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="rounded-lg border border-border/70 bg-background/45 p-4">
          <p className="text-sm text-muted-foreground">Product</p>
          <p className="mt-1 font-semibold">AI Web3 Founder Research Report</p>
          <p className="mt-2 text-sm leading-6 text-muted-foreground">
            $19 paid report offer with product, price, customer, and checkout link generated by the Stripe Agent.
          </p>
        </div>
        <Button asChild className="w-full">
          <a href={checkoutUrl} target={checkoutUrl.startsWith("http") ? "_blank" : "_self"}>
            Open checkout <ExternalLink className="size-4" />
          </a>
        </Button>
      </CardContent>
    </Card>
  );
}


