import { notFound } from "next/navigation";
import { CheckCircle2, ShieldCheck } from "lucide-react";
import { ReportDownloadButton } from "@/components/reports/report-download-button";
import { SiteHeader } from "@/components/marketing/site-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { generateCustomerReport } from "@/lib/fulfillment/report-generator";
import type { ReportSection } from "@/lib/fulfillment/templates";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

type PageProps = { params: { id: string } };

async function loadReport(id: string) {
  if (id === "demo-report") {
    const report = await generateCustomerReport({ orderId: "demo-report", customerName: "Demo Web3 Founder" });
    return { id, title: report.title, markdown: report.markdown, sections: report.sections, status: "delivered", provider: report.provider, order: null };
  }

  try {
    const saved = await prisma.fulfillmentReport.findUnique({
      where: { id },
      include: { order: true }
    });
    if (!saved) return null;
    return {
      id: saved.id,
      title: saved.title,
      markdown: saved.markdown,
      sections: JSON.parse(saved.sectionsJson) as ReportSection[],
      status: saved.status,
      provider: saved.provider,
      order: saved.order
    };
  } catch {
    return null;
  }
}

export default async function ReportPage({ params }: PageProps) {
  const report = await loadReport(params.id);
  if (!report) notFound();

  return (
    <main className="min-h-screen overflow-hidden">
      <SiteHeader />
      <section className="container pb-10 pt-4">
        <Card className="grid-radar border-primary/25 p-6 sm:p-8">
          <Badge>Delivered to customer</Badge>
          <div className="mt-5 flex flex-col justify-between gap-5 lg:flex-row lg:items-end">
            <div>
              <h1 className="text-4xl font-semibold sm:text-6xl">{report.title}</h1>
              <p className="mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">Professional fulfillment packet generated by the Ops Agent with deterministic seeded content and audit-ready delivery status.</p>
            </div>
            <ReportDownloadButton markdown={report.markdown} filename="web3-founder-market-signal-report.md" />
          </div>
        </Card>

        <div className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_0.9fr]">
          <Card>
            <CardHeader><CardTitle>Customer Report</CardTitle></CardHeader>
            <CardContent className="space-y-6">
              {report.sections.map((section) => (
                <section key={section.heading} className="rounded-lg border border-border/70 bg-background/45 p-4">
                  <h2 className="text-xl font-semibold">{section.heading}</h2>
                  <p className="mt-3 text-sm leading-7 text-muted-foreground">{section.body}</p>
                </section>
              ))}
            </CardContent>
          </Card>

          <div className="space-y-5">
            <Card>
              <CardHeader><CardTitle>Fulfillment Status</CardTitle></CardHeader>
              <CardContent className="space-y-3">
                <div className="flex items-center gap-3 rounded-lg border border-primary/30 bg-primary/10 p-3">
                  <CheckCircle2 className="size-5 text-primary" />
                  <div><p className="font-semibold">Delivered to customer</p><p className="text-sm text-muted-foreground">Status: {report.status}</p></div>
                </div>
                <div className="rounded-lg border border-border/70 bg-background/45 p-3"><p className="text-xs text-muted-foreground">Provider</p><p className="mt-1 font-semibold">{report.provider}</p></div>
                <div className="rounded-lg border border-border/70 bg-background/45 p-3"><p className="text-xs text-muted-foreground">Report ID</p><p className="mt-1 break-all font-semibold">{report.id}</p></div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-4 text-primary" /> Agent Fulfillment Timeline</CardTitle></CardHeader>
              <CardContent className="space-y-3">
                {["Order received", "Report generated", "Policy-safe sources checked", "Markdown delivery packet created", "Audit status marked delivered"].map((item, index) => (
                  <div key={item} className="flex gap-3 rounded-lg border border-border/70 bg-background/45 p-3">
                    <div className="flex size-8 shrink-0 items-center justify-center rounded-md bg-primary/10 text-xs font-semibold text-primary">{index + 1}</div>
                    <p className="text-sm leading-6 text-muted-foreground">{item}</p>
                  </div>
                ))}
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </main>
  );
}
