import type { AgentEvent, BudgetPolicy, BusinessPlan, GrowthPackage, LearningRecommendation, SpendDecision, SpendRequest } from "@/lib/agents/types";
import { runAuditAgent } from "@/lib/agents/audit-agent";
import { runCeoAgent, runCeoAgentWithLlm } from "@/lib/agents/ceo-agent";
import { runCfoAgent } from "@/lib/agents/cfo-agent";
import { runGrowthAgent, runGrowthAgentWithLlm } from "@/lib/agents/growth-agent";
import { runLearningAgent, runLearningAgentWithLlm } from "@/lib/agents/learning-agent";
import { runRiskAgent } from "@/lib/agents/risk-agent";
import { runSpendAgent } from "@/lib/agents/spend-agent";
import { generateCustomerReport } from "@/lib/fulfillment/report-generator";
import { prisma } from "@/lib/prisma";
import { createResearchReportCheckout } from "@/lib/stripe/checkout";

type StartRunInput = {
  goal: string;
  budgetCents: number;
  customerEmail?: string;
  mode: "stripe_test";
};

function payloadOf<T>(event: AgentEvent<T>) {
  return event.payload as T;
}

async function saveEvent(runId: string, event: AgentEvent) {
  return prisma.agentEvent.create({
    data: {
      businessRunId: runId,
      role: event.role,
      title: event.title,
      detail: event.detail,
      status: event.status,
      amountCents: event.amount != null ? Math.round(event.amount * 100) : undefined,
      payloadJson: JSON.stringify({ action: event.action, decision: event.decision, reason: event.reason, policyMatched: event.policyMatched, receiptId: event.receiptId, payload: event.payload })
    }
  });
}

function fallbackReason(error: unknown) {
  return `Hermes creative call failed or timed out, so deterministic fallback content was used visibly: ${error instanceof Error ? error.message : "unknown error"}`;
}

function markFallback<T>(event: AgentEvent<T>, error: unknown) {
  return { ...event, reason: fallbackReason(error), detail: `${event.detail} Hermes fallback used; policy and spend controls remained deterministic.` };
}

async function saveFailedEvent(runId: string, error: unknown) {
  const event = (error as { agentEvent?: AgentEvent }).agentEvent;
  if (event) {
    await saveEvent(runId, event);
  } else {
    const message = error instanceof Error ? error.message : "Business run failed.";
    await saveEvent(runId, { id: "evt_run_failed", role: "System", title: "Business run failed", detail: message, status: "failed", action: "run_business", decision: "blocked", reason: message, payload: { error: message }, timestamp: new Date().toISOString() });
  }
  await prisma.businessRun.update({ where: { id: runId }, data: { status: "failed" } });
}

export async function startBusinessRun(input: StartRunInput) {
  const budget = input.budgetCents / 100;
  const customerEmail = input.customerEmail ?? "founder@example.com";
  const events: AgentEvent[] = [];
  const run = await prisma.businessRun.create({ data: { goal: input.goal, mode: input.mode, status: "running", budgetCents: input.budgetCents } });

  try {
    let ceoEvent: AgentEvent<BusinessPlan>;
    try {
      ceoEvent = await runCeoAgentWithLlm(input.goal);
    } catch (error) {
      ceoEvent = markFallback(runCeoAgent(input.goal), error);
    }
    events.push(ceoEvent);
    await saveEvent(run.id, ceoEvent);
    await prisma.businessRun.update({ where: { id: run.id }, data: { status: "planned" } });

    const plan = payloadOf(ceoEvent);
    const cfoEvent = runCfoAgent(plan, budget);
    events.push(cfoEvent);
    await saveEvent(run.id, cfoEvent);
    await prisma.businessRun.update({ where: { id: run.id }, data: { status: "policy_created" } });

    const policy = payloadOf<BudgetPolicy>(cfoEvent);
    let growthEvent: AgentEvent<GrowthPackage>;
    try {
      growthEvent = await runGrowthAgentWithLlm(plan);
    } catch (error) {
      growthEvent = markFallback(runGrowthAgent(plan), error);
    }
    events.push(growthEvent);
    await saveEvent(run.id, growthEvent);
    await prisma.businessRun.update({ where: { id: run.id }, data: { status: "offer_created" } });

    const checkout = await createResearchReportCheckout({ customerEmail, productName: plan.offerName, amountCents: Math.round(plan.priceRecommendation * 100), businessRunId: run.id });
    await prisma.businessRun.update({ where: { id: run.id }, data: { status: "checkout_created" } });

    let report = await generateCustomerReport({ customerEmail, productName: plan.offerName, goal: input.goal });
    const reportReason = report.warning
      ? `Report content generated with deterministic fallback after Hermes timeout or validation issue. ${report.warning}`
      : "Report content generated with configured provider and stored for fulfillment.";
    const opsEvent: AgentEvent = { id: "evt_ops_report", role: "Ops", title: "Ops generated customer report", detail: `${report.title} generated by ${report.provider}.`, status: "fulfilled", action: "generate_customer_report", decision: "fulfilled", reason: reportReason, payload: report, timestamp: new Date().toISOString() };
    events.push(opsEvent);
    await saveEvent(run.id, opsEvent);
    await prisma.fulfillmentReport.create({ data: { businessRunId: run.id, orderId: checkout.orderId, title: report.title, markdown: report.markdown, sectionsJson: JSON.stringify(report.sections), status: "generated", provider: report.provider } });

    const spendEvent = runSpendAgent();
    const spendRequests = payloadOf<SpendRequest[]>(spendEvent);
    events.push(spendEvent);
    await saveEvent(run.id, spendEvent);
    for (const request of spendRequests) {
      await prisma.spendRequest.create({ data: { id: `${run.id}_${request.id}`, businessRunId: run.id, vendor: request.vendor, amountCents: Math.round(request.amount * 100), category: request.category, reason: request.purpose, riskLevel: request.risk, status: "requested" } });
    }

    const riskEvent = runRiskAgent(spendRequests, policy);
    const decisions = payloadOf<SpendDecision[]>(riskEvent);
    events.push(riskEvent);
    await saveEvent(run.id, riskEvent);

    let approvedCents = 0;
    let blockedCents = 0;
    for (const decision of decisions) {
      const amountCents = Math.round(decision.request.amount * 100);
      if (decision.decision === "approved") approvedCents += amountCents;
      if (decision.decision === "blocked") blockedCents += amountCents;
      await prisma.spendRequest.update({ where: { id: `${run.id}_${decision.request.id}` }, data: { status: decision.decision } });
      await prisma.policyDecision.create({ data: { businessRunId: run.id, spendRequestRef: `${run.id}_${decision.request.id}`, decision: decision.decision, reason: decision.reason, matchedRulesJson: JSON.stringify([decision.policyMatched]), remainingCents: input.budgetCents - approvedCents, receiptRequired: decision.decision === "approved", riskScore: decision.request.risk === "high" ? 90 : decision.request.risk === "medium" ? 55 : 20 } });
      await prisma.receipt.create({ data: { businessRunId: run.id, source: decision.request.vendor, amountCents, decision: decision.decision, note: decision.reason, externalId: decision.receiptId ?? decision.request.id } });
    }

    const auditEvent = runAuditAgent(events, decisions);
    events.push(auditEvent);
    await saveEvent(run.id, auditEvent);

    let learningEvent: AgentEvent<LearningRecommendation>;
    try {
      learningEvent = await runLearningAgentWithLlm(decisions);
    } catch (error) {
      learningEvent = markFallback(runLearningAgent(decisions), error);
    }
    events.push(learningEvent);
    await saveEvent(run.id, learningEvent);

    const revenueCents = 0;
    await prisma.businessRun.update({ where: { id: run.id }, data: { status: "awaiting_payment", costCents: approvedCents, blockedRiskCents: blockedCents, profitCents: revenueCents - approvedCents } });
    await prisma.profitLossReport.create({ data: { businessRunId: run.id, revenueCents, costCents: approvedCents, profitCents: revenueCents - approvedCents, blockedRiskCents: blockedCents, notes: "Business run started; revenue reconciles after Stripe webhook payment." } });

    const savedRun = await prisma.businessRun.findUnique({ where: { id: run.id }, include: { agentEvents: true, customerOrders: true, spendRequests: true, policyDecisions: true, receipts: true, profitLossReports: true, fulfillmentReports: true } });
    return { run: savedRun, checkout };
  } catch (error) {
    await saveFailedEvent(run.id, error);
    throw error;
  }
}


